(function () {
  "use strict";

  const node = (config) => ({
    model: "无 LLM",
    tools: [],
    inputs: [],
    outputs: [],
    route: "固定路由",
    promptZh: "这个节点不调用大模型，因此没有提示词。",
    promptEn: "This node does not invoke an LLM and has no prompt.",
    ...config,
  });

  const nodes = [
    node({
      id: "start", label: "运行输入", shortLabel: "输入", phase: "control", kind: "control",
      position: { x: 40, y: 210 }, source: "tradingagents/graph/propagation.py",
      summary: "创建共享 AgentState，注入股票代码、分析日期、资产类型、历史经验和已解析的标的信息。",
      inputs: ["ticker", "trade_date", "asset_type", "past_context"],
      outputs: ["AgentState", "messages"], route: "进入第一个被选中的分析师节点。",
    }),
    node({
      id: "market", label: "市场分析师", shortLabel: "市场", phase: "analysis", kind: "agent",
      position: { x: 250, y: 100 }, source: "tradingagents/agents/analysts/market_analyst.py",
      model: "Quick-thinking LLM", tools: ["get_stock_data", "get_indicators", "get_verified_market_snapshot"],
      inputs: ["messages", "trade_date", "instrument_context"], outputs: ["market_report", "messages"],
      route: "如果模型返回 tool_calls，进入市场工具节点；否则保存 market_report 并进入下一位分析师。",
      summary: "选择最多 8 个互补技术指标，先取行情，再计算指标，并用验证快照约束精确数字。",
      promptZh: `你是一名金融市场分析助手。请根据当前市场状态或交易策略，从给定清单中选择最多 8 个互补且不重复的指标：均线（50/200 SMA、10 EMA）、MACD 系列、RSI、布林带、ATR、VWMA。必须先调用 get_stock_data 获取价格数据，再调用 get_indicators；在最终报告前必须调用 get_verified_market_snapshot，并将其作为所有精确 OHLCV、价位和指标数值的事实来源。若不同工具的数据冲突，应明确指出差异，不得编造一个“协调后的数字”。除非工具输出含具体日期和价格，否则不得声称历史验证、支撑阻力反弹或精确涨跌幅。最终写出细致、有证据、可行动的趋势报告，并在结尾附 Markdown 汇总表。输出语言遵循运行配置。`,
      promptEn: `You are a trading assistant tasked with analyzing financial markets. Select up to 8 relevant, complementary indicators without redundancy. Call get_stock_data first, then get_indicators. Before the final report, call get_verified_market_snapshot and treat it as the source of truth for exact OHLCV, price-level, and indicator-value claims. Flag conflicts instead of inventing reconciled numbers. Write a detailed, nuanced and actionable report with a Markdown summary table.`,
    }),
    node({
      id: "market-tools", label: "市场数据工具", shortLabel: "市场工具", phase: "tool", kind: "tool",
      position: { x: 250, y: 330 }, source: "tradingagents/graph/trading_graph.py",
      tools: ["Yahoo Finance 行情", "技术指标", "验证快照"], inputs: ["tool_calls"], outputs: ["ToolMessage[]"],
      route: "执行模型请求的工具后回到市场分析师；可能发生多轮。",
      summary: "LangGraph ToolNode。它不思考，只按结构化 tool_calls 执行函数并把结果写回 messages。",
    }),
    node({
      id: "sentiment", label: "情绪分析师", shortLabel: "情绪", phase: "analysis", kind: "agent",
      position: { x: 500, y: 100 }, source: "tradingagents/agents/analysts/sentiment_analyst.py",
      model: "Quick-thinking LLM", tools: ["Yahoo Finance 新闻（预取）", "StockTwits（预取）", "Reddit（预取）"],
      inputs: ["ticker", "trade_date", "instrument_context", "三类预取数据"], outputs: ["sentiment_report", "messages"],
      route: "数据在调用 LLM 前由 Python 预取，无 tool_calls 回环；生成结构化情绪报告后进入下一位分析师。",
      summary: "把机构新闻、StockTwits 散户标签和 Reddit 讨论放进同一提示词，比较来源分歧与样本质量。",
      promptZh: `你是一名金融市场情绪分析师。针对 {ticker} 在 {start_date} 至 {end_date} 的情绪，综合三类已经预取的数据：Yahoo Finance 新闻标题（偏机构、事实驱动、信号较慢）、带 Bullish/Bearish 标签的 StockTwits 消息（快速散户信号）以及 Reddit 的 wallstreetbets、stocks、investing 讨论（结合点赞和评论衡量关注度）。分析 StockTwits 多空比例及真实样本量；寻找新闻与散户观点之间的分歧；按互动量加权 Reddit；区分事实事件和主观看法；识别反复出现的叙事、催化剂与风险；若数据缺失或样本少必须降低置信度。过去情绪不等于未来价格。输出 overall_band、0-10 overall_score、low/medium/high confidence，以及包含逐来源证据、分歧、主导叙事、催化剂、风险和 Markdown 汇总表的 narrative。`,
      promptEn: `You are a financial market sentiment analyst. Produce a comprehensive report for {ticker} using pre-fetched Yahoo Finance news, StockTwits messages with user sentiment tags, and Reddit posts. Consider sample size, cross-source divergences, engagement, event versus opinion, recurring narratives, catalysts, risks, and data limitations. Output an overall band, 0-10 score, confidence, and a source-by-source narrative with a Markdown table.`,
    }),
    node({
      id: "news", label: "新闻分析师", shortLabel: "新闻", phase: "analysis", kind: "agent",
      position: { x: 750, y: 100 }, source: "tradingagents/agents/analysts/news_analyst.py",
      model: "Quick-thinking LLM", tools: ["get_news", "get_global_news", "get_macro_indicators", "get_prediction_markets"],
      inputs: ["messages", "trade_date", "asset_type", "instrument_context"], outputs: ["news_report", "messages"],
      route: "有 tool_calls 时进入新闻工具节点；没有时保存 news_report。",
      summary: "研究最近一周的标的新闻、全球宏观新闻、FRED 指标和预测市场概率。",
      promptZh: `你是一名新闻研究员，负责分析最近一周与交易和宏观经济相关的新闻与趋势。使用 get_news 获取标的新闻，get_global_news 获取全球宏观新闻，get_macro_indicators 用 FRED 的 CPI、核心 PCE、失业率、联邦基金利率、10 年期国债和收益率曲线等真实数据约束宏观判断，并用 get_prediction_markets 获取降息、衰退、地缘政治或行业事件的市场隐含概率。写出全面、有证据、可行动的报告，并在末尾附 Markdown 汇总表。`,
      promptEn: `You are a news researcher analyzing recent news and trends over the past week. Use company-specific news, global macro news, FRED macro indicators, and prediction-market probabilities. Provide specific, actionable insights with supporting evidence and append a Markdown summary table.`,
    }),
    node({
      id: "news-tools", label: "新闻与宏观工具", shortLabel: "新闻工具", phase: "tool", kind: "tool",
      position: { x: 750, y: 330 }, source: "tradingagents/graph/trading_graph.py",
      tools: ["标的/全球新闻", "FRED", "预测市场", "内部人交易"], inputs: ["tool_calls"], outputs: ["ToolMessage[]"],
      route: "执行工具后回到新闻分析师，直到模型不再请求工具。",
      summary: "为新闻分析提供外部事实；不同供应商的失败会由 dataflow 层降级或抛出可诊断错误。",
    }),
    node({
      id: "fundamentals", label: "基本面分析师", shortLabel: "基本面", phase: "analysis", kind: "agent",
      position: { x: 1000, y: 100 }, source: "tradingagents/agents/analysts/fundamentals_analyst.py",
      model: "Quick-thinking LLM", tools: ["get_fundamentals", "get_balance_sheet", "get_cashflow", "get_income_statement"],
      inputs: ["messages", "trade_date", "instrument_context"], outputs: ["fundamentals_report", "messages"],
      route: "有 tool_calls 时进入基本面工具节点；没有时保存 fundamentals_report。加密资产模式通常过滤此节点。",
      summary: "汇总公司资料、财务历史和三大财务报表，形成面向交易者的基本面报告。",
      promptZh: `你是一名公司基本面研究员。分析过去一周的基本面信息，并结合公司档案、基础财务数据、财务历史、资产负债表、现金流量表和利润表，建立完整的公司视图。尽可能详细，但每项结论都应给出证据和对交易决策有用的行动含义。使用 get_fundamentals 获取综合分析，并用 get_balance_sheet、get_cashflow、get_income_statement 获取具体报表。末尾附 Markdown 汇总表。`,
      promptEn: `You are a researcher tasked with analyzing fundamental information over the past week. Cover financial documents, company profile, basic financials, financial history, balance sheet, cash flow, and income statement. Provide detailed, evidence-backed, actionable insights and append a Markdown summary table.`,
    }),
    node({
      id: "fundamentals-tools", label: "财务数据工具", shortLabel: "财务工具", phase: "tool", kind: "tool",
      position: { x: 1000, y: 330 }, source: "tradingagents/graph/trading_graph.py",
      tools: ["综合基本面", "资产负债表", "现金流量表", "利润表"], inputs: ["tool_calls"], outputs: ["ToolMessage[]"],
      route: "执行工具后回到基本面分析师，直到形成最终报告。",
      summary: "把财务供应商数据转换为 ToolMessage，供同一分析师下一轮读取。",
    }),
    node({
      id: "bull", label: "多头研究员", shortLabel: "多头", phase: "research", kind: "agent",
      position: { x: 1260, y: 70 }, source: "tradingagents/agents/researchers/bull_researcher.py",
      model: "Quick-thinking LLM", inputs: ["四类分析报告", "debate history", "last bear argument"],
      outputs: ["investment_debate_state.bull_history", "current_response", "count + 1"],
      route: "未达到 2 × 研究轮数时转给空头；达到上限时转给研究经理。",
      summary: "使用相同研究材料构造最强多头论证，并逐点反驳上一轮空头观点。",
      promptZh: `你是主张投资该股票或资产的多头分析师。建立强有力且有证据的看多案例，重点讨论增长潜力、竞争优势、积极指标，并针对空头论点用具体数据逐点反驳。读取市场、情绪、新闻、基本面报告，以及完整辩论历史和上一轮空头发言。以对话式辩论表达，不要只是罗列事实；应说明为什么多头解释更有说服力。输出会追加到 bull_history 和共享 debate history。`,
      promptEn: `You are a Bull Analyst advocating for investing in the stock or asset. Build a strong evidence-based case around growth potential, competitive advantages, positive indicators, and direct rebuttals to the bear argument. Use all analyst reports, debate history, and the last bear argument. Engage conversationally rather than merely listing data.`,
    }),
    node({
      id: "bear", label: "空头研究员", shortLabel: "空头", phase: "research", kind: "agent",
      position: { x: 1260, y: 260 }, source: "tradingagents/agents/researchers/bear_researcher.py",
      model: "Quick-thinking LLM", inputs: ["四类分析报告", "debate history", "last bull argument"],
      outputs: ["investment_debate_state.bear_history", "current_response", "count + 1"],
      route: "未达到 2 × 研究轮数时转给多头；达到上限时转给研究经理。",
      summary: "使用同一批材料构造最强风险案例，揭示弱点并反驳上一轮多头观点。",
      promptZh: `你是反对投资该股票或资产的空头分析师。建立逻辑严密的风险案例，重点讨论市场饱和、财务不稳定、宏观威胁、竞争弱点、负面指标，并用具体数据揭示多头论证的漏洞或过度乐观假设。读取市场、情绪、新闻、基本面报告，以及完整辩论历史和上一轮多头发言。以直接交锋的对话方式论证，而不是简单罗列事实。输出会追加到 bear_history 和共享 debate history。`,
      promptEn: `You are a Bear Analyst making the case against investing in the stock or asset. Emphasize risks, competitive weaknesses, negative indicators, and direct evidence-based counterpoints to bullish assumptions. Use all reports, the debate history, and the last bull argument in a conversational debate.`,
    }),
    node({
      id: "research-manager", label: "研究经理", shortLabel: "研究裁决", phase: "manager", kind: "agent",
      position: { x: 1500, y: 165 }, source: "tradingagents/agents/managers/research_manager.py",
      model: "Deep-thinking LLM", inputs: ["investment_debate_state.history", "instrument_context"],
      outputs: ["investment_plan", "judge_decision"], route: "固定进入交易员。",
      summary: "裁判多空辩论，输出 Buy/Overweight/Hold/Underweight/Sell 五档结构化研究计划。",
      promptZh: `你是研究经理兼辩论主持人。批判性评估完整多空辩论，并为交易员交付清晰、可执行的投资计划。必须从 Buy、Overweight、Hold、Underweight、Sell 中选择一档：证据明显偏向一方时应明确表态，仅在双方证据真正均衡时使用 Hold。计划需要吸收辩论中最强的事实与反驳，并通过结构化输出形成 investment_plan。`,
      promptEn: `As the Research Manager and debate facilitator, critically evaluate the debate and deliver a clear, actionable investment plan. Use exactly one rating: Buy, Overweight, Hold, Underweight, or Sell. Commit to a stance when warranted and reserve Hold for genuinely balanced evidence.`,
    }),
    node({
      id: "trader", label: "交易员", shortLabel: "交易方案", phase: "trading", kind: "agent",
      position: { x: 1740, y: 165 }, source: "tradingagents/agents/trader/trader.py",
      model: "Quick-thinking LLM", inputs: ["investment_plan", "instrument_context", "company_of_interest"],
      outputs: ["trader_investment_plan", "messages"], route: "固定进入激进风险分析师。",
      summary: "把研究经理的方向性意见转换成具体的交易提案。",
      promptZh: `你是一名根据市场数据作出投资决策的交易员。以分析师报告和研究经理的 investment_plan 为基础，对目标标的给出明确的买入、卖出或持有建议，并形成具体交易提案。需要继承研究计划中的技术趋势、宏观指标和情绪证据，不得脱离上游材料另起炉灶。输出采用 TraderProposal 结构；若供应商不支持结构化输出则退回自由文本。`,
      promptEn: `You are a trading agent analyzing market data to make investment decisions. Provide a specific buy, sell, or hold recommendation anchored in the analysts' reports and the Research Manager's investment plan. Turn that plan into an informed, strategic transaction proposal.`,
    }),
    node({
      id: "aggressive", label: "激进风险分析师", shortLabel: "激进", phase: "risk", kind: "agent",
      position: { x: 1980, y: 50 }, source: "tradingagents/agents/risk_mgmt/aggressive_debator.py",
      model: "Quick-thinking LLM", inputs: ["trader plan", "四类报告", "risk history", "其他风险观点"],
      outputs: ["risk_debate_state.aggressive_history", "latest_speaker", "count + 1"],
      route: "未达到 3 × 风险轮数时转给保守分析师；达到上限时可进入投资组合经理。",
      summary: "主动主张高风险高回报路径，反驳保守和中立观点。",
      promptZh: `你是激进风险分析师，主动主张高回报、高风险机会。审查交易员方案，突出潜在上行、增长潜力和创新优势，并用市场、情绪、新闻、基本面报告反驳保守与中立分析师。读取完整风险辩论历史和两位对手的最新观点；若尚无对手观点，则基于现有数据独立立论。重点是辩论与说服，不是复述数据；以自然对话文本输出。`,
      promptEn: `As the Aggressive Risk Analyst, champion high-reward, high-risk opportunities. Evaluate the trader's plan, emphasize upside and innovation, use all reports, and directly rebut conservative and neutral arguments. Focus on debating and persuading, not merely presenting data.`,
    }),
    node({
      id: "conservative", label: "保守风险分析师", shortLabel: "保守", phase: "risk", kind: "agent",
      position: { x: 1980, y: 190 }, source: "tradingagents/agents/risk_mgmt/conservative_debator.py",
      model: "Quick-thinking LLM", inputs: ["trader plan", "四类报告", "risk history", "其他风险观点"],
      outputs: ["risk_debate_state.conservative_history", "latest_speaker", "count + 1"],
      route: "未达到上限时转给中立分析师；达到上限时可进入投资组合经理。",
      summary: "以资产保护、低波动和可持续性为目标，寻找方案的下行风险。",
      promptZh: `你是保守风险分析师，首要目标是保护资产、降低波动并维持稳定增长。审查交易员方案中的高风险部分、经济下行与市场波动，提出更谨慎的替代路径。读取四类报告、完整辩论历史，以及激进和中立分析师的最新观点，逐点指出他们忽略的威胁或不可持续假设。重点是辩论和批判，以自然对话文本输出。`,
      promptEn: `As the Conservative Risk Analyst, protect assets, minimize volatility, and ensure steady growth. Identify high-risk elements and overlooked threats in the trader's plan, directly counter aggressive and neutral arguments, and advocate a sustainable low-risk adjustment.`,
    }),
    node({
      id: "neutral", label: "中立风险分析师", shortLabel: "中立", phase: "risk", kind: "agent",
      position: { x: 1980, y: 330 }, source: "tradingagents/agents/risk_mgmt/neutral_debator.py",
      model: "Quick-thinking LLM", inputs: ["trader plan", "四类报告", "risk history", "其他风险观点"],
      outputs: ["risk_debate_state.neutral_history", "latest_speaker", "count + 1"],
      route: "未达到上限时回到激进分析师；达到上限时可进入投资组合经理。",
      summary: "同时挑战激进和保守两端，寻找风险收益更平衡的调整。",
      promptZh: `你是中立风险分析师，平衡交易方案的潜在收益和风险，并考虑宏观变化、市场趋势和分散化。读取四类报告、完整辩论历史，以及激进和保守分析师的最新观点；指出一方过度乐观、另一方过度谨慎之处，主张兼顾增长与极端波动防护的可持续方案。重点是对双方论点进行辩论，而不是简单汇总。`,
      promptEn: `As the Neutral Risk Analyst, weigh the benefits and risks of the trader's plan. Challenge both aggressive and conservative perspectives, use all reports and debate history, and advocate a balanced strategy that preserves growth potential while guarding against extreme volatility.`,
    }),
    node({
      id: "portfolio-manager", label: "投资组合经理", shortLabel: "最终裁决", phase: "manager", kind: "agent",
      position: { x: 2250, y: 165 }, source: "tradingagents/agents/managers/portfolio_manager.py",
      model: "Deep-thinking LLM", inputs: ["investment_plan", "trader plan", "risk history", "past_context"],
      outputs: ["final_trade_decision", "risk judge_decision"], route: "固定进入成功结束；成功后清除本次 checkpoint。",
      summary: "综合研究、交易、风险辩论与历史经验，形成最终五档投资组合决策。",
      promptZh: `你是投资组合经理。综合风险分析师辩论，交付最终交易决策。必须从 Buy、Overweight、Hold、Underweight、Sell 中选择一档。上下文包括研究经理的投资计划、交易员的具体提案、历史决策及结果沉淀出的经验（若存在），以及完整风险辩论。结论必须果断，并把每项判断落到分析师提供的具体证据上。输出 PortfolioDecision 结构并渲染为 final_trade_decision。`,
      promptEn: `As the Portfolio Manager, synthesize the risk debate and deliver the final decision using exactly one rating: Buy, Overweight, Hold, Underweight, or Sell. Consider the research plan, trader proposal, lessons from prior outcomes, and full risk debate. Be decisive and ground conclusions in specific evidence.`,
    }),
    node({
      id: "checkpoint", label: "SQLite Checkpoint", shortLabel: "断点", phase: "storage", kind: "storage",
      position: { x: 1220, y: 500 }, source: "tradingagents/graph/checkpointer.py",
      inputs: ["每个已完成节点的状态", "ticker + date + graph signature"], outputs: ["可恢复状态"],
      route: "失败时保留；同参数重跑时恢复；成功后删除对应线程状态。",
      summary: "LangGraph SqliteSaver。graph signature 包含分析师选择、研究深度、风险深度和资产类型。",
    }),
    node({
      id: "memory", label: "跨次运行记忆", shortLabel: "记忆", phase: "storage", kind: "storage",
      position: { x: 2250, y: 500 }, source: "tradingagents/agents/utils/memory.py",
      inputs: ["final_trade_decision", "后续真实收益", "反思"], outputs: ["past_context"],
      route: "本次决策写入 pending；下次同标的运行前计算结果并把经验注入起始状态和最终经理。",
      summary: "Markdown 记忆日志，不是向量数据库；把同标的经验和跨标的教训带入未来运行。",
    }),
    node({
      id: "end", label: "最终输出", shortLabel: "输出", phase: "control", kind: "control",
      position: { x: 2480, y: 165 }, source: "tradingagents/graph/trading_graph.py",
      inputs: ["final_trade_decision", "完整 AgentState"], outputs: ["报告树", "BUY/HOLD/SELL 信号", "memory entry"],
      route: "终止图运行；保存报告和决策，成功时清理 checkpoint。",
      summary: "最终评级由 SignalProcessor 解析，不再额外调用 LLM。",
    }),
  ];

  const edges = [
    { id: "market-tool", source: "market", target: "market-tools", kind: "conditional", label: "有 tool_calls" },
    { id: "market-loop", source: "market-tools", target: "market", kind: "loop", label: "工具结果" },
    { id: "news-tool", source: "news", target: "news-tools", kind: "conditional", label: "有 tool_calls" },
    { id: "news-loop", source: "news-tools", target: "news", kind: "loop", label: "工具结果" },
    { id: "fund-tool", source: "fundamentals", target: "fundamentals-tools", kind: "conditional", label: "有 tool_calls" },
    { id: "fund-loop", source: "fundamentals-tools", target: "fundamentals", kind: "loop", label: "工具结果" },
    { id: "bull-bear", source: "bull", target: "bear", kind: "conditional", label: "下一位：Bear" },
    { id: "bear-bull", source: "bear", target: "bull", kind: "loop", label: "下一轮：Bull" },
    { id: "bull-manager", source: "bull", target: "research-manager", kind: "conditional", label: "达到 2 × rounds" },
    { id: "bear-manager", source: "bear", target: "research-manager", kind: "conditional", label: "达到 2 × rounds" },
    { id: "manager-trader", source: "research-manager", target: "trader", kind: "fixed", label: "investment_plan" },
    { id: "trader-aggressive", source: "trader", target: "aggressive", kind: "fixed", label: "交易提案" },
    { id: "aggressive-conservative", source: "aggressive", target: "conservative", kind: "conditional", label: "下一位" },
    { id: "conservative-neutral", source: "conservative", target: "neutral", kind: "conditional", label: "下一位" },
    { id: "neutral-aggressive", source: "neutral", target: "aggressive", kind: "loop", label: "下一轮" },
    { id: "aggressive-pm", source: "aggressive", target: "portfolio-manager", kind: "conditional", label: "达到 3 × rounds" },
    { id: "conservative-pm", source: "conservative", target: "portfolio-manager", kind: "conditional", label: "达到 3 × rounds" },
    { id: "neutral-pm", source: "neutral", target: "portfolio-manager", kind: "conditional", label: "达到 3 × rounds" },
    { id: "pm-end", source: "portfolio-manager", target: "end", kind: "fixed", label: "final decision" },
    { id: "memory-start", source: "memory", target: "start", kind: "memory", label: "past_context" },
    { id: "end-memory", source: "end", target: "memory", kind: "memory", label: "存储决策" },
    { id: "checkpoint-start", source: "checkpoint", target: "start", kind: "persistence", label: "失败后恢复" },
    { id: "end-checkpoint", source: "end", target: "checkpoint", kind: "persistence", label: "成功后清除" },
  ];

  globalThis.WorkflowData = Object.freeze({
    version: "TradingAgents v0.3.1 / local fork 3221069",
    analystOrder: ["market", "sentiment", "news", "fundamentals"],
    toolNodeByAnalyst: { market: "market-tools", news: "news-tools", fundamentals: "fundamentals-tools" },
    nodes,
    edges,
    stateFields: [
      { group: "运行上下文", fields: ["company_of_interest", "trade_date", "asset_type", "instrument_context", "past_context"] },
      { group: "分析报告", fields: ["market_report", "sentiment_report", "news_report", "fundamentals_report"] },
      { group: "研究阶段", fields: ["investment_debate_state", "investment_plan"] },
      { group: "交易阶段", fields: ["trader_investment_plan"] },
      { group: "风险与结果", fields: ["risk_debate_state", "final_trade_decision"] },
    ],
  });
})();
